name=libe131
version=1.4.0
author=Hugo Hromic
maintainer=Hugo Hromic
sentence=Transmit and receive DMX using E1.31 (sACN).
paragraph=This is a lightweight C/C++ library that provides a simple API for packet, client and server programming to be used for communicating with devices implementing the E1.31 (sACN) protocol.
category=Communication
url=https://github.com/hhromic/libe131
architectures=esp32
